#!/usr/bin/env python3
"""
PR Review Web Interface - 交互式PR审查工具
在浏览器中审查和合并Pull Request
"""

from flask import Flask, render_template, jsonify, request
import json
import subprocess
import threading
import time
import os
import signal
import sys
import atexit

# 获取项目根目录（上一级目录）
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
PR_DATA_FILE = os.path.join(SCRIPT_DIR, 'pr_data.json')

app = Flask(__name__)

# 全局状态
current_state = {
    'current_pr': None,
    'temp_branch': None,
    'original_branch': None,
    'docker_running': False,
    'preview_url': 'http://localhost:4000/CS163-Projects-2025Fall/',
    'status': 'idle',
    'message': '',
    'prs': [],
    'stats': {
        'total': 0,
        'reviewed': 0,
        'accepted': 0,
        'skipped': 0
    },
    'file_changes': {
        'accepted': [],
        'rejected': [],
        'edited': []
    }
}

def run_command(cmd, capture=True, check=True):
    """运行shell命令（在项目根目录执行）"""
    try:
        if capture:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, check=check, timeout=30, cwd=PROJECT_ROOT)
            return {'success': True, 'output': result.stdout.strip(), 'error': ''}
        else:
            subprocess.run(cmd, shell=True, check=check, timeout=30, cwd=PROJECT_ROOT)
            return {'success': True, 'output': '', 'error': ''}
    except subprocess.CalledProcessError as e:
        return {'success': False, 'output': '', 'error': e.stderr if capture else str(e)}
    except subprocess.TimeoutExpired:
        return {'success': False, 'output': '', 'error': 'Command timeout'}
    except Exception as e:
        return {'success': False, 'output': '', 'error': str(e)}

def load_pull_requests():
    """加载PR列表"""
    try:
        # 先尝试从文件加载
        if os.path.exists(PR_DATA_FILE):
            with open(PR_DATA_FILE, 'r') as f:
                return json.load(f)
    except:
        pass
    
    # 从GitHub获取
    result = run_command('curl -s "https://api.github.com/repos/UCLAdeepvision/CS163-Projects-2025Fall/pulls?state=open&per_page=100"', capture=True, check=False)
    if result['success'] and result['output']:
        try:
            prs = json.loads(result['output'])
            # 保存到文件
            with open(PR_DATA_FILE, 'w') as f:
                json.dump(prs, f, indent=2)
            return prs
        except:
            pass
    return []

def get_current_branch():
    """获取当前分支"""
    result = run_command("git branch --show-current", capture=True, check=False)
    return result['output'] if result['success'] else 'main'

def post_github_comment(pr_number, comment_body):
    """发布评论到GitHub PR"""
    try:
        import json
        comment_json = json.dumps({'body': comment_body})
        # 使用curl发送评论（需要GitHub token）
        # 先检查是否有GITHUB_TOKEN环境变量
        import os
        token = os.environ.get('GITHUB_TOKEN', '')
        
        if not token:
            print("Warning: GITHUB_TOKEN not set, skipping comment")
            return False
        
        cmd = f'''curl -X POST \
            -H "Authorization: token {token}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/UCLAdeepvision/CS163-Projects-2025Fall/issues/{pr_number}/comments \
            -d '{comment_json}' '''
        
        result = run_command(cmd, capture=True, check=False)
        return result['success']
    except Exception as e:
        print(f"Failed to post comment: {e}")
        return False

def generate_review_comment(accepted_files, rejected_files, edited_files=None):
    """生成审查评论内容 (英文)"""
    comment = "## 🤖 Automated Review Report\n\n"
    
    if accepted_files:
        comment += f"### ✅ Accepted Files ({len(accepted_files)})\n"
        for f in accepted_files[:20]:  # 最多显示20个
            comment += f"- `{f}`\n"
        if len(accepted_files) > 20:
            comment += f"- ... and {len(accepted_files) - 20} more files\n"
        comment += "\n"
    
    if rejected_files:
        comment += f"### ❌ Rejected Files ({len(rejected_files)})\n"
        comment += "_These files are not in the allowed directories (assets/, _posts/)_\n\n"
        for f in rejected_files[:20]:
            comment += f"- `{f}`\n"
        if len(rejected_files) > 20:
            comment += f"- ... and {len(rejected_files) - 20} more files\n"
        comment += "\n"
    
    if edited_files:
        comment += f"### ✏️ Edited Files ({len(edited_files)})\n"
        comment += "_These files were modified during the review process_\n\n"
        for f in edited_files:
            comment += f"- `{f}`\n"
        comment += "\n"
    
    comment += "---\n"
    comment += "_This comment was automatically generated by the review tool_"
    
    return comment

def start_docker_background():
    """在后台启动Docker"""
    current_state['status'] = 'starting_docker'
    current_state['message'] = '正在启动Docker预览...'
    
    # 先停止现有容器
    run_command("docker compose down", capture=False, check=False)
    time.sleep(2)
    
    # 启动容器（不用build）
    result = run_command("docker compose up -d", capture=False, check=False)
    
    if result['success']:
        current_state['docker_running'] = True
        current_state['status'] = 'docker_ready'
        current_state['message'] = f'Docker已启动！请访问: {current_state["preview_url"]}'
    else:
        current_state['docker_running'] = False
        current_state['status'] = 'docker_error'
        current_state['message'] = f'Docker启动失败: {result["error"]}'

def stop_docker():
    """停止Docker"""
    run_command("docker compose down", capture=False, check=False)
    current_state['docker_running'] = False
    current_state['message'] = 'Docker已停止'

def cleanup_branch():
    """清理临时分支"""
    if current_state['temp_branch']:
        # 检查是否有未提交的更改
        run_command("git reset --hard", capture=False, check=False)
        
        # 清理未跟踪的文件（_site/等）
        run_command("rm -rf _site/", capture=False, check=False)
        run_command("git clean -fd", capture=False, check=False)
        
        # 返回原始分支
        if current_state['original_branch']:
            run_command(f"git checkout {current_state['original_branch']}", capture=False, check=False)
        
        # 删除临时分支
        run_command(f"git branch -D {current_state['temp_branch']}", capture=False, check=False)
        
        current_state['temp_branch'] = None

def cleanup_on_exit():
    """退出时的清理函数"""
    print("\n\n收到退出信号，正在清理...")
    
    # 停止Docker
    print("停止Docker容器...")
    stop_docker()
    
    # 清理Git状态
    try:
        current_branch = get_current_branch()
        print(f"当前分支: {current_branch}")
        
        # 如果在review分支上，需要清理
        if current_branch and current_branch.startswith('review-pr-'):
            print(f"检测到临时分支: {current_branch}")
            
            # 重置任何未提交的更改
            print("重置未提交的更改...")
            run_command("git reset --hard", capture=False, check=False)
            
            # 清理未跟踪的文件
            print("清理未跟踪的文件...")
            run_command("rm -rf _site/", capture=False, check=False)
            run_command("git clean -fd", capture=False, check=False)
            
            # 返回main分支
            print("返回main分支...")
            result = run_command("git checkout main", capture=False, check=False)
            
            if result['success']:
                print(f"✓ 已切换到main分支")
                
                # 删除临时分支
                print(f"删除临时分支: {current_branch}")
                run_command(f"git branch -D {current_branch}", capture=False, check=False)
                print(f"✓ 已删除临时分支")
            else:
                print(f"⚠️  切换分支失败，可能需要手动清理")
                print(f"请手动运行: git checkout main && git branch -D {current_branch}")
        
        # 如果有记录的临时分支（防止状态不一致）
        if current_state['temp_branch'] and current_state['temp_branch'] != current_branch:
            print(f"清理记录的临时分支: {current_state['temp_branch']}")
            run_command(f"git branch -D {current_state['temp_branch']}", capture=False, check=False)
    
    except Exception as e:
        print(f"清理时出错: {e}")
        print("可能需要手动清理Git状态")
    
    print("\n✓ 清理完成")
    print("再见！👋\n")

def signal_handler(sig, frame):
    """处理Ctrl+C信号"""
    cleanup_on_exit()
    sys.exit(0)

@app.route('/')
def index():
    """主页"""
    return render_template('pr_review.html')

@app.route('/api/prs')
def get_prs():
    """获取PR列表"""
    if not current_state['prs']:
        current_state['prs'] = load_pull_requests()
        current_state['stats']['total'] = len(current_state['prs'])
    
    prs_data = []
    for i, pr in enumerate(current_state['prs'], 1):
        prs_data.append({
            'index': i,
            'number': pr['number'],
            'title': pr['title'],
            'author': pr['user']['login'],
            'branch': f"{pr['head']['label']} -> {pr['base']['ref']}",
            'created_at': pr['created_at'],
            'url': pr['html_url']
        })
    
    return jsonify({
        'success': True,
        'prs': prs_data,
        'stats': current_state['stats']
    })

@app.route('/api/status')
def get_status():
    """获取当前状态"""
    return jsonify({
        'success': True,
        'status': current_state['status'],
        'message': current_state['message'],
        'docker_running': current_state['docker_running'],
        'preview_url': current_state['preview_url'],
        'current_pr': current_state['current_pr'],
        'stats': current_state['stats']
    })

@app.route('/api/prepare_pr', methods=['POST'])
def prepare_pr():
    """准备审查PR"""
    data = request.json
    pr_index = data.get('index', 0) - 1
    
    if pr_index < 0 or pr_index >= len(current_state['prs']):
        return jsonify({'success': False, 'error': 'Invalid PR index'})
    
    pr = current_state['prs'][pr_index]
    current_state['current_pr'] = {
        'index': pr_index + 1,
        'number': pr['number'],
        'title': pr['title'],
        'author': pr['user']['login'],
        'branch': f"{pr['head']['label']} -> {pr['base']['ref']}"
    }
    
    current_state['status'] = 'preparing'
    current_state['message'] = f'正在准备PR #{pr["number"]}...'
    
    # 在后台线程中执行准备工作
    def prepare_thread():
        try:
            pr_number = pr['number']
            pr_head_ref = pr['head']['ref']
            pr_head_repo = pr['head']['repo']
            temp_branch = f"review-pr-{pr_number}"
            
            current_state['temp_branch'] = temp_branch
            current_state['original_branch'] = get_current_branch()
            
            # 0. 清理可能残留的未跟踪文件
            current_state['message'] = '清理工作区...'
            # 清理 _site/ 目录（Jekyll生成的，不应该提交）
            run_command("rm -rf _site/", capture=False, check=False)
            # 清理可能残留的 Gemfile.lock（如果是未跟踪的）
            run_command("git clean -fd", capture=False, check=False)
            
            # 1. 创建临时分支（如果已存在则先删除）
            current_state['message'] = '创建临时分支...'
            # 检查分支是否存在
            check_branch = run_command(f"git rev-parse --verify {temp_branch}", capture=True, check=False)
            if check_branch['success']:
                # 分支已存在，先删除
                run_command(f"git branch -D {temp_branch}", capture=False, check=False)
            
            result = run_command(f"git checkout -b {temp_branch}", capture=False, check=False)
            if not result['success']:
                current_state['status'] = 'error'
                current_state['message'] = f'创建分支失败: {result["error"]}'
                return
            
            # 2. 更新main
            current_state['message'] = '更新main分支...'
            run_command(f"git fetch origin main", capture=False, check=False)
            
            # 3. 合并main
            current_state['message'] = '合并main到临时分支...'
            result = run_command(f"git merge origin/main --no-edit", capture=False, check=False)
            
            # 4. 获取并合并PR
            current_state['message'] = f'获取并合并PR #{pr_number}...'
            if pr_head_repo:
                head_repo_url = pr_head_repo['clone_url']
                run_command(f"git fetch {head_repo_url} {pr_head_ref}", capture=False, check=False)
            else:
                run_command(f"git fetch origin pull/{pr_number}/head", capture=False, check=False)
            
            result = run_command(f"git merge FETCH_HEAD --no-edit", capture=False, check=False)
            
            if not result['success']:
                # 检查是否有冲突
                conflict_check = run_command("git diff --name-only --diff-filter=U", capture=True, check=False)
                if conflict_check['success'] and conflict_check['output']:
                    current_state['status'] = 'conflict'
                    current_state['message'] = f'合并冲突: {conflict_check["output"]}'
                    current_state['stats']['skipped'] += 1
                    current_state['stats']['reviewed'] += 1
                    cleanup_branch()
                    current_state['current_pr'] = None
                    return
            
            # 检查修改的文件，只保留 assets/ 和 _posts/ 目录下的修改
            current_state['message'] = '检查并过滤修改的文件...'
            changed_files = run_command("git diff --name-only origin/main", capture=True, check=False)
            if changed_files['success'] and changed_files['output']:
                files = changed_files['output'].split('\n')
                valid_files = []
                invalid_files = []
                
                for f in files:
                    f = f.strip()
                    if not f:
                        continue
                    if f.startswith('assets/') or f.startswith('_posts/'):
                        valid_files.append(f)
                    else:
                        invalid_files.append(f)
                
                # 记录文件变化
                current_state['file_changes']['accepted'] = valid_files
                current_state['file_changes']['rejected'] = invalid_files
                current_state['file_changes']['edited'] = []
                
                if invalid_files:
                    # 有不允许的文件，需要过滤
                    current_state['message'] = f'过滤不允许的文件: {len(invalid_files)} 个'
                    
                    if not valid_files:
                        # 没有有效文件，直接跳过
                        current_state['status'] = 'no_valid_files'
                        current_state['message'] = f'❌ PR不包含允许的文件修改\n只允许修改 assets/ 和 _posts/ 目录'
                        current_state['stats']['skipped'] += 1
                        current_state['stats']['reviewed'] += 1
                        cleanup_branch()
                        current_state['current_pr'] = None
                        return
                    
                    # 重置到origin/main，然后只保留允许的文件
                    run_command("git reset --hard origin/main", capture=False, check=False)
                    
                    # 从PR获取并只checkout允许的文件
                    if pr_head_repo:
                        head_repo_url = pr_head_repo['clone_url']
                        run_command(f"git fetch {head_repo_url} {pr_head_ref}", capture=False, check=False)
                    else:
                        run_command(f"git fetch origin pull/{pr_number}/head", capture=False, check=False)
                    
                    # 只checkout允许的文件
                    for vf in valid_files:
                        run_command(f"git checkout FETCH_HEAD -- {vf}", capture=False, check=False)
                    
                    # 提交过滤后的修改
                    run_command("git add -A", capture=False, check=False)
                    commit_msg = f"Filtered changes from PR #{pr_number} (only assets/ and _posts/)"
                    run_command(f'git commit -m "{commit_msg}"', capture=False, check=False)
                    
                    current_state['message'] = f'✓ 已过滤 {len(invalid_files)} 个不允许的文件，保留 {len(valid_files)} 个有效文件'
            
            # 5. 启动Docker
            start_docker_background()
            
        except Exception as e:
            current_state['status'] = 'error'
            current_state['message'] = f'错误: {str(e)}'
            cleanup_branch()
    
    thread = threading.Thread(target=prepare_thread)
    thread.daemon = True
    thread.start()
    
    return jsonify({'success': True, 'message': 'Started preparing PR'})

@app.route('/api/get_file_summary')
def get_file_summary():
    """获取文件变更摘要"""
    return jsonify({
        'success': True,
        'accepted': len(current_state['file_changes']['accepted']),
        'rejected': len(current_state['file_changes']['rejected']),
        'edited': len(current_state['file_changes']['edited'])
    })

@app.route('/api/generate_comment')
def generate_comment_api():
    """生成评论内容"""
    comment = generate_review_comment(
        current_state['file_changes']['accepted'],
        current_state['file_changes']['rejected'],
        current_state['file_changes']['edited']
    )
    return jsonify({'success': True, 'comment': comment})

@app.route('/api/check_edited_files')
def check_edited_files():
    """检查哪些文件被编辑了"""
    try:
        # 使用git diff检查修改的文件
        result = run_command("git diff --name-only", capture=True, check=False)
        
        if result['success'] and result['output']:
            files = result['output'].strip().split('\n')
            # 只保留accepted的文件
            edited_files = [f for f in files if f in current_state['file_changes']['accepted']]
            
            # 更新状态
            current_state['file_changes']['edited'] = edited_files
            
            # 自动git add这些文件
            for f in edited_files:
                run_command(f"git add {f}", capture=False, check=False)
            
            return jsonify({
                'success': True,
                'edited_files': edited_files
            })
        else:
            return jsonify({
                'success': True,
                'edited_files': []
            })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e),
            'edited_files': []
        })

@app.route('/api/accept_pr', methods=['POST'])
def accept_pr():
    """接受并合并PR"""
    if not current_state['current_pr']:
        return jsonify({'success': False, 'error': 'No PR is being reviewed'})
    
    # 获取自定义评论和额外评论
    data = request.json or {}
    custom_comment = data.get('custom_comment', '').strip()
    additional_comment = data.get('additional_comment', '').strip()
    
    current_state['status'] = 'accepting'
    current_state['message'] = '正在合并到main...'
    
    def accept_thread():
        try:
            # 停止Docker
            stop_docker()
            time.sleep(1)
            
            pr_number = current_state['current_pr']['number']
            pr_title = current_state['current_pr']['title']
            pr_branch = current_state['current_pr']['branch']
            temp_branch = current_state['temp_branch']
            
            # 切换到main
            current_state['message'] = '切换到main分支...'
            result = run_command("git checkout main", capture=False, check=False)
            if not result['success']:
                current_state['status'] = 'error'
                current_state['message'] = f'切换到main失败: {result["error"]}'
                return
            
            # 拉取最新的main
            current_state['message'] = '拉取最新的main...'
            run_command("git pull origin main", capture=False, check=False)
            
            # 合并临时分支到main
            current_state['message'] = f'合并PR #{pr_number}到main...'
            merge_cmd = f"git merge {temp_branch} --no-ff -m 'Merge pull request #{pr_number}\\n\\n{pr_title}'"
            result = run_command(merge_cmd, capture=False, check=False)
            
            if result['success']:
                current_state['stats']['accepted'] += 1
                current_state['stats']['reviewed'] += 1
                current_state['status'] = 'accepted'
                current_state['message'] = f'✓ PR #{pr_number} 已成功合并到main！记得运行 git push origin main'
                
                # 发送GitHub comment
                current_state['message'] += '\n正在发送审查报告...'
                
                # 使用自定义评论或自动生成
                if custom_comment:
                    comment_body = custom_comment
                else:
                    comment_body = generate_review_comment(
                        current_state['file_changes']['accepted'],
                        current_state['file_changes']['rejected'],
                        current_state['file_changes']['edited']
                    )
                
                # 附加额外评论
                if additional_comment:
                    comment_body += f"\n\n## 💡 Additional Comments\n\n{additional_comment}"
                
                if post_github_comment(pr_number, comment_body):
                    current_state['message'] += '\n✓ 审查报告已发送到GitHub'
                else:
                    current_state['message'] += '\n⚠️  审查报告发送失败（需要设置GITHUB_TOKEN）'
            else:
                current_state['status'] = 'error'
                current_state['message'] = f'合并失败: {result["error"]}'
                run_command("git merge --abort", capture=False, check=False)
            
            # 清理
            cleanup_branch()
            current_state['current_pr'] = None
            
        except Exception as e:
            current_state['status'] = 'error'
            current_state['message'] = f'错误: {str(e)}'
    
    thread = threading.Thread(target=accept_thread)
    thread.daemon = True
    thread.start()
    
    return jsonify({'success': True, 'message': 'Started accepting PR'})

@app.route('/api/skip_pr', methods=['POST'])
def skip_pr():
    """跳过PR"""
    if not current_state['current_pr']:
        return jsonify({'success': False, 'error': 'No PR is being reviewed'})
    
    pr_number = current_state['current_pr']['number']
    
    # 停止Docker
    stop_docker()
    
    # 清理
    cleanup_branch()
    
    current_state['stats']['skipped'] += 1
    current_state['stats']['reviewed'] += 1
    current_state['status'] = 'skipped'
    current_state['message'] = f'已跳过PR #{pr_number}'
    current_state['current_pr'] = None
    
    return jsonify({'success': True, 'message': 'PR skipped'})

@app.route('/api/refresh_prs', methods=['POST'])
def refresh_prs():
    """刷新PR列表"""
    current_state['prs'] = load_pull_requests()
    current_state['stats']['total'] = len(current_state['prs'])
    return jsonify({'success': True, 'message': 'PR list refreshed', 'count': len(current_state['prs'])})

@app.route('/api/restart_docker', methods=['POST'])
def restart_docker():
    """重启Docker"""
    stop_docker()
    time.sleep(1)
    
    thread = threading.Thread(target=start_docker_background)
    thread.daemon = True
    thread.start()
    
    return jsonify({'success': True, 'message': 'Restarting Docker'})

@app.route('/api/get_files')
def get_files():
    """获取当前PR的可编辑文件列表"""
    if not current_state['current_pr']:
        return jsonify({'success': False, 'error': 'No PR is being reviewed'})
    
    files = current_state['file_changes']['accepted']
    return jsonify({'success': True, 'files': files})

@app.route('/api/read_file', methods=['POST'])
def read_file_content():
    """读取文件内容"""
    data = request.json
    file_path = data.get('path', '')
    
    if not file_path:
        return jsonify({'success': False, 'error': 'No file path provided'})
    
    # 安全检查：只允许读取accepted的文件
    if file_path not in current_state['file_changes']['accepted']:
        return jsonify({'success': False, 'error': 'File not in accepted list'})
    
    full_path = os.path.join(PROJECT_ROOT, file_path)
    try:
        with open(full_path, 'r', encoding='utf-8') as f:
            content = f.read()
        return jsonify({'success': True, 'content': content})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

@app.route('/api/save_file', methods=['POST'])
def save_file_content():
    """保存编辑的文件"""
    data = request.json
    file_path = data.get('path', '')
    content = data.get('content', '')
    
    if not file_path:
        return jsonify({'success': False, 'error': 'No file path provided'})
    
    # 安全检查：只允许保存accepted的文件
    if file_path not in current_state['file_changes']['accepted']:
        return jsonify({'success': False, 'error': 'File not in accepted list'})
    
    full_path = os.path.join(PROJECT_ROOT, file_path)
    try:
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # 标记为已编辑
        if file_path not in current_state['file_changes']['edited']:
            current_state['file_changes']['edited'].append(file_path)
        
        # 提交更改
        run_command(f"git add {file_path}", capture=False, check=False, cwd=PROJECT_ROOT)
        
        return jsonify({'success': True, 'message': f'File {file_path} saved'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})

if __name__ == '__main__':
    # 注册信号处理器
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    
    # 注册退出时的清理函数
    atexit.register(cleanup_on_exit)
    
    print("="*80)
    print("PR Review Web Interface")
    print("="*80)
    print("\n请在浏览器中访问: http://localhost:5001")
    print("\n按 Ctrl+C 停止服务器（会自动清理临时分支）\n")
    
    # 加载PR列表
    current_state['prs'] = load_pull_requests()
    current_state['stats']['total'] = len(current_state['prs'])
    
    try:
        # 启动Flask应用
        app.run(debug=False, host='0.0.0.0', port=5001, use_reloader=False)
    except KeyboardInterrupt:
        # Flask已经捕获了Ctrl+C，但我们的signal_handler会处理
        pass

